!excellence Suport for TUM Bot
timschumi/TUMbot pull request #4
Opened 2019-11-26 15:02 UTC by CommanderStorm

The Bot defenitively needs some !excellence

2019-11-27 11:01 UTC, NiOHar commented
It's quite an excellent feature ;)
Defo nice to have.

2019-11-27 21:45 UTC, timschumi requested changes
Maybe somehow make this use the same codebase as the Quotes thing that this is based on?
Another option would be to generate the message on-the-fly (combination of subject + exzellent/trivial).

Also, I'm not sure about the usefulness of this in general, I don't really think it's a funny addition at all.

2019-11-27 21:45 UTC, timschumi commented on exzellenz.txt
> +PgDP ist sehr exzellent.
PGdP

2019-11-27 21:45 UTC, timschumi commented on exzellenz.txt
> +EiDI ist sehr exzellent.
EidI

2019-11-27 21:45 UTC, timschumi commented on exzellenz.txt
> +Die Bockabfertigung in der Mensa ist sehr exzellent.
Bockabfertigung?

2019-11-27 21:45 UTC, timschumi commented on exzellenz.txt
> +PgDP ist mir zu trivial.
PGdP

2019-11-27 21:45 UTC, timschumi commented on exzellenz.txt
> +EiDI ist mir zu trivial.
EidI

2019-11-28 10:55 UTC, CommanderStorm commented on exzellenz.txt
> +Die Bockabfertigung in der Mensa ist sehr exzellent.
Ja, Blockabfertigung.
https://mensa.liste.party/

2019-11-28 11:26 UTC, CommanderStorm commented
I think the separation of the "UserGeneratedContent" (I know the name is not that good, but I cant think of a more fitting one) into its own folder was nessesary, as now there is more than one file and because this cleans things up a notch..

2019-11-28 11:28 UTC, CommanderStorm commented
different files for trivial/excellence were neccesary, as some of the things dont really make sense in the other context. (i.e. "Die Mensa ist trivial")

2019-11-28 19:05 UTC, timschumi commented
I'm not really convinced by the code quality yet, I'll see if I can make a few changes in the next days.

2019-11-29 17:21 UTC, timschumi commented
I fixed some of the major issues I had with this. However, some of the strings are still nonsensical, so please redistribute them across the two lists (`exzellenz_extra` are taken as is, `exzellenz_trivial` is extended with either "ist sehr exzellent" or "ist trivial").

If the result uses more than those two lists, I'll just reject and lock this Pull Request, because this should not take that much effort to be maintained, and I don't feel like importing a module that requires this much effort to be maintained, seeing how this is neither useful nor funny.

2019-12-04 03:30 UTC, merged