changed the sceduling to the sceduling packet
timschumi/TUMbot pull request #46
Opened 2020-05-22 23:51 UTC by CommanderStorm

Reason for this Pull request:

- no more birthdays at 16:xx
- no more mensa updates at 16:xx (dont know if that happened, but that could have happened)
- sceduling the python way

Drawbacks:

- need to reload the module
- posibility less output of errors on the console, as only the error can be outputet

2020-05-23 00:16 UTC, timschumi requested changes

2020-05-23 00:16 UTC, timschumi commented on bot.py
> +    def register_job_dayly(self, daytime, f):
daily

2020-05-23 11:30 UTC, timschumi commented
Also, could we do this by assigning a new Scheduler to bot explicitly instead of using the default Scheduler instance?

2020-05-23 13:48 UTC, CommanderStorm commented
tested this. 
It (status+birthday) works.

(mensa does not really work, but that is the api's/virus fault for disrupting the whole eating on campus thing..)

2020-05-24 00:03 UTC, timschumi approved these changes
Looks fine.

2020-05-24 00:04 UTC, merged